name: test-gh-actions # workflow name

on: [push]# triggering event
  # schedule:
   # - cron: '0 9 * * 1'

jobs: # groups all the jobs ran in this workflow
#----------
# JOB 1
#----------
  test-HPA-version: # name of the first job
    runs-on: ubuntu-latest # The type of runner that the job will run on
    container: bioconductor/bioconductor_docker:devel
    
    steps: # group all the steps in the job named test-HPA-version
   
       - uses: actions/checkout@master # an action that checks out your repository and downloads it to the runner, allowing you to run actions against your code
       
       - name: Install latest hpar
         run:  Rscript -e "BiocManager::install('lgatto/hpar')"
         
       - name: Check HPA release
        ## This will fail if there's a new version
         run: Rscript -e "stop()"
        # run: Rscript -e "stopifnot(!hpar:::newHpaVersion())"
       
#------------------ 
# conditional JOB 2
#------------------ 
  if-failure: # name of the second job
     runs-on: ubuntu-latest # The type of runner that the job will run on
     if: failure() #failure() or always()
     needs: test-HPA-version
     
     steps: # group all the steps in the job named if-failure
     
       - uses: actions/checkout@master # an action that checks out your repository and downloads it to the runner, allowing you to run actions against your code
   
       - name: Send a slack message
         uses: rtCamp/action-slack-notify@v2
         env:
           SLACK_COLOR: '#76D7C4'
           SLACK_MESSAGE: ':seedling: a new version of HPA is available'
           SLACK_TITLE: hpar version check
           SLACK_USERNAME: hparBot
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     
       - uses: JasonEtco/create-an-issue@v2 # create an issue on GitHub
         id: create-issue
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           filename: .github/issue-template.md
           
       - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
       - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
         
 
